# Copyright 2025 Canonical Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""GRUB utils.

Phase-B (unprivileged-container friendly) GRUB installation.

The previous flow used ``losetup`` + a real chroot with a ``devtmpfs``
mount and ran ``grub-install`` against the loop device. Both ``losetup``
and ``mount -t devtmpfs`` require capabilities that aren't available in
an unprivileged user namespace (init_user_ns CAP_SYS_ADMIN), so neither
works inside an unprivileged LXD container.

The new flow:

  * Runs *inside* the rootfs prime directory (the tree produced by
    ``mmdebstrap`` + apt). That tree IS the chroot — no image mounts,
    no loop devices.
  * Replaces the ``devtmpfs`` mount with a ``--bind`` of the host's
    ``/dev`` (LXD pre-populates a usable ``/dev``).
  * Produces the bootloader bytes (``boot.img``, ``core.img``, signed
    shim/grub EFI binaries, an ESP grub.cfg stub) and stages them so
    that:
       - the rootfs prime dir already contains ``/boot/grub/grub.cfg``
         when ``mke2fs -d`` reads it in;
       - the system-boot (ESP) prime dir already contains
         ``EFI/BOOT/BOOTX64.EFI`` and friends when ``mkfs.vfat`` +
         ``mcopy`` reads it in;
       - ``boot.img`` is ``dd``'d into MBR bytes 0-440 of the final
         disk image *after* the image is finalised;
       - ``core.img`` is ``dd``'d into the BIOS-boot partition (ef02)
         on GPT, or into the post-MBR gap on plain MBR.

Scope: amd64 only (covers both x86_64-efi UEFI and i386-pc BIOS).
arm64 / armhf / riscv64 emit a TODO progress message and return
without doing anything — see :func:`setup_grub` for the entry point.
"""

import dataclasses
import shutil
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

from craft_cli import emit
from craft_platforms import DebianArchitecture

from imagecraft import errors
from imagecraft.models.volume import (
    GptType,
    PartitionSchema,
    Role,
    StructureItem,
)
from imagecraft.pack import gptutil
from imagecraft.pack.chroot import Chroot, Mount
from imagecraft.subprocesses import run

if TYPE_CHECKING:
    from collections.abc import Mapping

    from imagecraft.models.volume import Volume
    from imagecraft.pack.image import Image


# ── Constants ─────────────────────────────────────────────────────────────────

_GRUB_EFI_TARGET_X86_64 = "x86_64-efi"
_GRUB_BIOS_TARGET = "i386-pc"

# MBR boot code lives in bytes 0..440. Bytes 440..512 are the disk
# signature + partition table; we must NOT clobber them.
_MBR_BOOTCODE_LEN = 440
_SECTOR_SIZE = 512

# Modules embedded in core.img. This matches what `grub-install
# --target=i386-pc` ships into the BIOS-boot partition for an Ubuntu
# pc-style image. Keep biosdisk + part_{gpt,msdos} + ext2/fat + search/
# normal/linux so the core can find /boot/grub/grub.cfg on either GPT or
# MBR layouts.
_CORE_IMG_MODULES = [
    "biosdisk",
    "part_gpt",
    "part_msdos",
    "ext2",
    "fat",
    "search",
    "search_label",
    "search_fs_uuid",
    "search_fs_file",
    "normal",
    "linux",
    "configfile",
]

# Chainload stub written to /EFI/ubuntu/grub.cfg on the ESP. Tells the
# signed grub on the ESP to hand off to the kernel-listing grub.cfg on
# the rootfs partition. The rootfs is found by filesystem-label
# ("writable" — see the default project schema in models/volume.py).
_ESP_GRUB_CFG_STUB = """\
# Auto-generated by imagecraft. Chainload to the kernel-listing grub.cfg
# on the rootfs partition.
search.fs_label writable root
set prefix=($root)/boot/grub
configfile $prefix/grub.cfg
"""

_OS_PROBER_PATH = "/etc/grub.d/30_os-prober"


# ── Public API ────────────────────────────────────────────────────────────────


@dataclasses.dataclass
class GrubAssets:
    """Bytes that must be written to the final disk image after assembly.

    Produced by :func:`prepare_grub_assets` *before* partition format,
    consumed by :func:`install_grub_to_image` *after* finalisation.
    """

    boot_img: Path | None = None
    """Path to the 512-byte i386-pc boot.img. dd'd into MBR bytes 0..440."""

    core_img: Path | None = None
    """Path to a grub-mkimage-produced core.img. dd'd into the BIOS-boot
    (ef02) partition for GPT layouts, or into the post-MBR gap for plain
    MBR layouts."""

    bios_boot_partition_name: str | None = None
    """Name of the GPT ef02 partition that core.img should be written
    to. ``None`` for MBR (where core.img goes into the post-MBR gap)."""


def setup_grub(
    image: "Image",
    workdir: Path,
    arch: str,
    prime_dirs: "Mapping[str, Path]",
    volume_name: str,
) -> None:
    """Install GRUB on the image (post-finalisation orchestration).

    This is the legacy entry point retained for ``services/pack.py``.
    It runs :func:`prepare_grub_assets` and :func:`install_grub_to_image`
    in sequence — but in production we want
    :func:`prepare_grub_assets` to run BEFORE the partition format step
    (so the prime dirs are populated before ``mke2fs -d`` /
    ``mcopy``), and :func:`install_grub_to_image` to run AFTER
    finalisation. ``services/pack.py`` calls them separately.

    Kept here as a single-shot helper for tests and for callers that
    don't need pre-format population.
    """
    assets = prepare_grub_assets(
        arch=arch,
        volume_name=volume_name,
        volume=image.volume,
        prime_dirs=prime_dirs,
        workdir=workdir,
    )
    if assets is not None:
        install_grub_to_image(image=image, assets=assets)


def prepare_grub_assets(  # noqa: PLR0912 — phase-B orchestration is inherently branchy
    *,
    arch: str,
    volume_name: str,
    volume: "Volume",
    prime_dirs: "Mapping[str, Path]",
    workdir: Path,
) -> GrubAssets | None:
    """Prepare grub assets without any image mount or loop device.

    Runs ``update-grub`` + ``grub-mkimage`` inside the rootfs prime dir
    (using a bind-mounted /dev rather than devtmpfs), populates the ESP
    prime dir with shim + signed grub + a chainload grub.cfg stub, and
    extracts ``boot.img`` and ``core.img`` for later ``dd`` into the
    final image.

    Returns ``None`` if grub installation is skipped (no data partition,
    unsupported architecture, etc.). Otherwise returns a
    :class:`GrubAssets` describing the bytes still to be written
    post-assembly.
    """
    emit.progress("Setting up GRUB in the image")

    # Architecture gate. Only amd64 is implemented for Phase B; other
    # arches emit a TODO and return None so the caller does nothing.
    if arch != DebianArchitecture.AMD64:
        # i386 falls into the BIOS-only path historically — Phase B
        # doesn't try to handle it. Same TODO treatment as arm64/etc.
        emit.progress(
            f"TODO: Phase B grub install not yet implemented for {arch}",
            permanent=True,
        )
        return None

    # Locate the rootfs (system-data) and boot (system-boot) prime dirs
    # via the project's structure list.
    rootfs_struct = _find_structure(volume, Role.SYSTEM_DATA)
    if rootfs_struct is None:
        emit.progress(
            "Skipping GRUB installation because no data partition was found",
            permanent=True,
        )
        return None

    boot_struct = _find_structure(volume, Role.SYSTEM_BOOT)

    schema = volume.volume_schema
    if schema == PartitionSchema.GPT and boot_struct is None:
        emit.progress(
            "Skipping GRUB installation because no boot partition was found",
            permanent=True,
        )
        return None

    rootfs_prime = prime_dirs[f"volume/{volume_name}/{rootfs_struct.name}"]
    boot_prime: Path | None = None
    if boot_struct is not None:
        boot_prime = prime_dirs[f"volume/{volume_name}/{boot_struct.name}"]

    # Locate BIOS-boot (ef02) partition if present — only meaningful on
    # GPT. MBR core.img goes into the post-MBR gap instead.
    bios_boot_struct: StructureItem | None = None
    if schema == PartitionSchema.GPT:
        bios_boot_struct = _find_bios_boot_structure(volume)

    # Stage the chroot mount points. We chroot directly into the rootfs
    # prime dir — no image partition mounts. /dev is a --bind (not
    # devtmpfs) so unprivileged user namespaces work.
    _ensure_chroot_mountpoints(rootfs_prime)
    mounts = _phase_b_chroot_mounts()
    chroot = Chroot(path=rootfs_prime, mounts=mounts)

    workdir.mkdir(parents=True, exist_ok=True)
    assets_dir = workdir / "grub-assets"
    assets_dir.mkdir(parents=True, exist_ok=True)

    # Compute the -p prefix for core.img. On GPT the BIOS-boot
    # partition's core.img loads grub modules from /boot/grub on the
    # rootfs partition (which is `gpt2` in a typical efi+rootfs layout
    # or `gpt3` when there's a separate /boot, etc.). We point at the
    # rootfs partition by partition number.
    rootfs_partnum = _partition_number(volume, rootfs_struct)
    if schema == PartitionSchema.GPT:
        core_prefix = f"(,gpt{rootfs_partnum})/boot/grub"
    else:
        core_prefix = f"(,msdos{rootfs_partnum})/boot/grub"

    try:
        chroot.execute(
            target=_build_grub_in_chroot,
            core_prefix=core_prefix,
        )
    except errors.ChrootMountError as err:
        emit.progress(
            f"Cannot install GRUB on this rootfs: {err}", permanent=True
        )
        return None

    # Pull boot.img and core.img out of the rootfs (they live at known
    # paths inside the chroot).
    boot_img_src = rootfs_prime / "usr/lib/grub/i386-pc/boot.img"
    core_img_src = rootfs_prime / "tmp/imagecraft-core.img"

    boot_img_dst: Path | None = None
    core_img_dst: Path | None = None

    if boot_img_src.is_file():
        boot_img_dst = assets_dir / "boot.img"
        shutil.copy2(boot_img_src, boot_img_dst)
    else:
        emit.progress(
            f"WARNING: boot.img not found at {boot_img_src}; "
            "MBR bytes 0..440 will not be written.",
            permanent=True,
        )

    if core_img_src.is_file():
        core_img_dst = assets_dir / "core.img"
        shutil.move(str(core_img_src), str(core_img_dst))
    else:
        emit.progress(
            f"WARNING: core.img not produced at {core_img_src}; "
            "no BIOS bootloader will be installed.",
            permanent=True,
        )

    # Populate the ESP prime dir with shim + signed grub + chainload
    # stub. mkfs.vfat + mcopy will then embed them into the ESP at
    # format time.
    if boot_prime is not None:
        _populate_esp_prime_dir(rootfs_prime=rootfs_prime, esp_prime=boot_prime)

    return GrubAssets(
        boot_img=boot_img_dst,
        core_img=core_img_dst,
        bios_boot_partition_name=(
            bios_boot_struct.name if bios_boot_struct is not None else None
        ),
    )


def install_grub_to_image(image: "Image", assets: GrubAssets) -> None:
    """Write boot.img + core.img into the final disk image.

    Uses ``dd`` against the image file directly (no loop device).
    """
    if assets.boot_img is None and assets.core_img is None:
        return

    disk_path = image.disk_path

    # MBR bytes 0..440 = i386-pc boot.img. Bytes 440..512 are the disk
    # signature + partition table — preserved by writing only the first
    # 440 bytes (count=440 bs=1 conv=notrunc).
    if assets.boot_img is not None:
        emit.progress(f"Writing i386-pc boot.img to MBR of {disk_path}")
        run(
            "dd",
            f"if={assets.boot_img}",
            f"of={disk_path}",
            "bs=1",
            f"count={_MBR_BOOTCODE_LEN}",
            "conv=notrunc",
            stderr=subprocess.STDOUT,
        )

    # core.img placement.
    if assets.core_img is not None:
        if assets.bios_boot_partition_name is not None:
            # GPT path: dd core.img into the BIOS-boot (ef02) partition.
            sector = gptutil.get_partition_sector_offset(
                disk_path, assets.bios_boot_partition_name
            )
            emit.progress(
                f"Writing GRUB core.img to BIOS-boot partition "
                f"{assets.bios_boot_partition_name!r} at sector {sector}"
            )
            run(
                "dd",
                f"if={assets.core_img}",
                f"of={disk_path}",
                f"bs={_SECTOR_SIZE}",
                f"seek={sector}",
                "conv=notrunc",
                stderr=subprocess.STDOUT,
            )
        else:
            # MBR path: dd core.img into the post-MBR gap (starting at
            # sector 1, ending before the first partition — usually
            # 2048 sectors of slack).
            emit.progress(
                f"Writing GRUB core.img to post-MBR gap of {disk_path}"
            )
            run(
                "dd",
                f"if={assets.core_img}",
                f"of={disk_path}",
                f"bs={_SECTOR_SIZE}",
                "seek=1",
                "conv=notrunc",
                stderr=subprocess.STDOUT,
            )


# ── Internals ─────────────────────────────────────────────────────────────────


def _find_structure(volume: "Volume", role: Role) -> StructureItem | None:
    """Return the first structure item with the given role, or None."""
    for item in volume.structure:
        if item.role == role:
            return item
    return None


def _find_bios_boot_structure(volume: "Volume") -> StructureItem | None:
    """Return the GPT BIOS-boot (ef02) partition, if present."""
    for item in volume.structure:
        st = getattr(item, "structure_type", None)
        if st == GptType.BIOS_BOOT:
            return item
    return None


def _partition_number(volume: "Volume", target: StructureItem) -> int:
    """Return the 1-based partition number for ``target`` within the volume.

    Matches the simple position-based numbering used by the GPT/MBR
    image creation paths. Honours an explicit ``partition_number`` on
    GPT items.
    """
    for i, item in enumerate(volume.structure, start=1):
        if item.name == target.name:
            explicit = getattr(item, "partition_number", None)
            return int(explicit) if explicit is not None else i
    # Should never happen — caller already located the structure.
    raise errors.ImageError(
        f"Cannot determine partition number for {target.name!r}"
    )


def _ensure_chroot_mountpoints(rootfs_prime: Path) -> None:
    """Make sure /dev, /proc, /sys, /run, /dev/pts exist under the rootfs.

    A properly-built mmdebstrap rootfs will already have these, but
    create them defensively so the chroot mount step doesn't fail on a
    bare directory.
    """
    for sub in ("dev", "proc", "sys", "run", "dev/pts"):
        (rootfs_prime / sub).mkdir(parents=True, exist_ok=True)


def _phase_b_chroot_mounts() -> list[Mount]:
    """Mounts for the in-rootfs grub work.

    Key difference vs the legacy flow: /dev is a ``--bind`` of the host
    ``/dev`` (LXD pre-populates it) instead of ``-t devtmpfs``. devtmpfs
    is blocked in non-init user namespaces by the kernel.
    """
    return [
        Mount(
            fstype=None,
            src="/dev",
            relative_mountpoint="/dev",
            options=["--bind"],
        ),
        Mount(
            fstype="devpts",
            src="devpts-build",
            relative_mountpoint="/dev/pts",
            options=["-o", "nodev,nosuid"],
        ),
        Mount(fstype="proc", src="proc-build", relative_mountpoint="proc"),
        Mount(fstype="sysfs", src="sysfs-build", relative_mountpoint="/sys"),
        Mount(
            fstype=None,
            src="/run",
            relative_mountpoint="/run",
            options=["--bind"],
        ),
    ]


def _build_grub_in_chroot(core_prefix: str) -> None:
    """Run inside the rootfs chroot: update-grub + grub-mkimage.

    Produces ``/boot/grub/grub.cfg`` (so it lands in the rootfs prime
    dir naturally, since the rootfs prime dir IS the chroot path) and
    ``/tmp/imagecraft-core.img`` (which the parent process then moves
    out to a known location).

    Does NOT call ``grub-install`` — that would need a target device.
    The MBR boot.img and the core.img are written by the parent process
    after the disk image is assembled.
    """
    # update-grub writes /boot/grub/grub.cfg by scanning /boot for
    # kernels. We keep the os-prober diversion from the legacy flow so
    # the chroot doesn't pick up the host's other operating systems.
    divert_args = [
        "--local",
        "--divert",
        _OS_PROBER_PATH + ".dpkg-divert",
        "--rename",
        _OS_PROBER_PATH,
    ]

    try:
        run("update-grub", "-V", stderr=subprocess.STDOUT)
    except FileNotFoundError:
        emit.progress(
            "Skipping GRUB installation because update-grub is not available",
            permanent=True,
        )
        return

    try:
        run("dpkg-divert", *divert_args, stderr=subprocess.STDOUT)
        try:
            res = run("update-grub", stderr=subprocess.STDOUT)
            if res.stdout:
                emit.debug(res.stdout)
        finally:
            run(
                "dpkg-divert",
                "--remove",
                *divert_args,
                stderr=subprocess.STDOUT,
            )
    except subprocess.CalledProcessError as err:
        raise errors.GRUBInstallError("Failed to run update-grub") from err

    # grub-mkimage to produce the BIOS core.img. The -p prefix tells
    # the core where to find /boot/grub on the final disk.
    try:
        run(
            "grub-mkimage",
            "-O",
            _GRUB_BIOS_TARGET,
            "-p",
            core_prefix,
            "-o",
            "/tmp/imagecraft-core.img",  # noqa: S108 — inside the chroot's tmp
            *_CORE_IMG_MODULES,
            stderr=subprocess.STDOUT,
        )
    except FileNotFoundError:
        emit.progress(
            "grub-mkimage not available — core.img will not be built",
            permanent=True,
        )
    except subprocess.CalledProcessError as err:
        raise errors.GRUBInstallError("Failed to build grub core.img") from err


def _populate_esp_prime_dir(rootfs_prime: Path, esp_prime: Path) -> None:
    """Lay out ESP contents in the boot prime dir.

    Looks up the signed shim + signed grub binaries inside the rootfs
    chroot (filenames vary across Ubuntu releases — survey at runtime)
    and copies them into the ESP prime dir at the canonical paths:

        EFI/BOOT/BOOTX64.EFI      — shim (fallback boot path)
        EFI/ubuntu/shimx64.efi    — same shim
        EFI/ubuntu/grubx64.efi    — signed grub
        EFI/ubuntu/grub.cfg       — chainload stub

    The rootfs's kernel-listing grub.cfg already lives in
    ``/boot/grub/grub.cfg`` thanks to ``update-grub`` — and since the
    rootfs prime dir IS the chroot path, that file lands in the rootfs
    partition naturally at format time.
    """
    shim_src = _find_first_existing(
        rootfs_prime,
        [
            "usr/lib/shim/shimx64.efi.signed.latest",
            "usr/lib/shim/shimx64.efi.signed",
            "usr/lib/shim/shimx64.efi.signed.previous",
        ],
    )
    grub_src = _find_first_existing(
        rootfs_prime,
        [
            "usr/lib/grub/x86_64-efi-signed/grubx64.efi.signed",
            "usr/lib/grub/x86_64-efi-signed/gcdx64.efi.signed",
        ],
    )

    if shim_src is None:
        raise errors.GRUBInstallError(
            "No signed shim binary found in rootfs. "
            "Expected usr/lib/shim/shimx64.efi.signed[.latest] — "
            "ensure the 'shim-signed' package is installed."
        )
    if grub_src is None:
        raise errors.GRUBInstallError(
            "No signed grub EFI binary found in rootfs. "
            "Expected usr/lib/grub/x86_64-efi-signed/grubx64.efi.signed — "
            "ensure the 'grub-efi-amd64-signed' package is installed."
        )

    efi_boot = esp_prime / "EFI" / "BOOT"
    efi_ubuntu = esp_prime / "EFI" / "ubuntu"
    efi_boot.mkdir(parents=True, exist_ok=True)
    efi_ubuntu.mkdir(parents=True, exist_ok=True)

    shutil.copy2(shim_src, efi_boot / "BOOTX64.EFI")
    shutil.copy2(shim_src, efi_ubuntu / "shimx64.efi")
    shutil.copy2(grub_src, efi_ubuntu / "grubx64.efi")
    (efi_ubuntu / "grub.cfg").write_text(_ESP_GRUB_CFG_STUB)


def _find_first_existing(base: Path, candidates: list[str]) -> Path | None:
    """Return the first ``base/cand`` that is an existing file, or None."""
    for cand in candidates:
        p = base / cand
        if p.is_file():
            return p
    return None
