name: imagecraft
base: core24
summary: Imagecraft is a craft tool used to create Ubuntu bootable images.
description: |
  Imagecraft is a craft tool used to create Ubuntu bootable images. It follows
  the same principles as snapcraft, but is focused on creating bootable images
  instead.
adopt-info: imagecraft
confinement: classic
grade: devel
license: GPL-3.0
source-code: https://github.com/canonical/imagecraft

platforms:
  amd64:
  arm64:
  armhf:
  riscv64:
  s390x:
  ppc64el:

apps:
  imagecraft:
    command: bin/python3 $SNAP/bin/imagecraft
    environment:
      PATH: "$SNAP/libexec/imagecraft:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      PERL5LIB: $SNAP/usr/share/perl5:$SNAP/usr/share/perl:$PERL5LIB
    completer: completion.sh

build-packages:
  - git
  - libapt-pkg-dev
  - libyaml-dev
  - python3.12-dev
  - python3.12-venv
  - pkg-config
  - python3-pip
  - python3-setuptools
  - python3-wheel
  - python3-venv
  - python3-minimal
  - python3-pkg-resources
  - python3.12-minimal

parts:
  libgit2:
    source: https://github.com/libgit2/libgit2/archive/refs/tags/v1.7.2.tar.gz
    source-checksum: sha256/de384e29d7efc9330c6cdb126ebf88342b5025d920dcb7c645defad85195ea7f
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DBUILD_TESTS=OFF
    build-attributes:
      - enable-patchelf
    build-packages:
      - libssl-dev
    prime:
      - -usr/include
      - -usr/bin
  imagecraft-libs:
    plugin: nil
    build-attributes:
      - enable-patchelf
    stage-packages:
      - apt
      - apt-transport-https
      - apt-utils
      - gpgv
      - libpython3-stdlib
      - libpython3.12-stdlib
      - libpython3.12-minimal
      - python-apt-common
      - python3-apt
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-pkg-resources
      - python3.12-venv
      - python3.12-minimal
      - python3-minimal
      - mtools
      - dosfstools
      - e2fsprogs
      - fdisk
      - coreutils
      - util-linux
    organize:
      "usr/lib/python3/dist-packages/apt*": "lib/python3.12/site-packages/"
      "usr/sbin/sfdisk": "libexec/imagecraft/sfdisk"
      "usr/bin/mcopy": "libexec/imagecraft/mcopy"
      "usr/bin/mtools": "libexec/imagecraft/mtools"
      "usr/bin/dd": "libexec/imagecraft/dd"
      "usr/bin/truncate": "libexec/imagecraft/truncate"
      "usr/sbin/mkfs*": "libexec/imagecraft/"
  fuse-overlayfs:
    after: [imagecraft-libs]
    source: https://github.com/containers/fuse-overlayfs.git
    source-tag: v1.15
    plugin: autotools
    build-attributes:
      - enable-patchelf
    build-packages:
      - libfuse3-dev
    stage-packages:
      - libfuse3-3
    organize:
      "fuse-overlayfs": "libexec/imagecraft/fuse-overlayfs"
  imagecraft:
    after: [imagecraft-libs, libgit2]
    source: .
    plugin: uv
    build-attributes:
      - enable-patchelf
    build-packages:
      - libffi-dev
      - cargo
      - pkg-config
      - git
    build-snaps:
      - astral-uv
    build-environment:
      - "CFLAGS": "$(pkg-config python-3.12 yaml-0.1 --cflags)"
      - UV_COMPILE_BYTECODE: "1"
      - UV_NO_BINARY: "1"
      - MAKEOPTS: -j$(nproc --all)
    organize:
      bin/craftctl: libexec/imagecraft/craftctl
    override-build: |
      ${SNAP}/libexec/snapcraft/craftctl default
      sed -i -e '1 s|^#!/.*|#!/snap/imagecraft/current/bin/python -E|' $CRAFT_PART_INSTALL/bin/craftctl
      version="$(PYTHONPATH=$CRAFT_PART_INSTALL/lib/python3.12/site-packages "${CRAFT_STAGE}/usr/bin/python3" -c "import imagecraft;print(imagecraft.__version__)")"
      ${SNAP}/libexec/snapcraft/craftctl set version="$version"

      rm $CRAFT_PART_INSTALL/bin/python*
      ln -s ../usr/bin/python3 $CRAFT_PART_INSTALL/bin/python3
      ln -s python3 $CRAFT_PART_INSTALL/bin/python

  bash-completion:
    after: [imagecraft]
    plugin: nil
    build-environment:
      - PYTHONPATH: $CRAFT_STAGE/lib/python3.12/site-packages
    override-build: |
      python3 -m craft_cli.completion $CRAFT_PROJECT_NAME imagecraft.cli:get_app_info \
        > $CRAFT_PART_INSTALL/completion.sh
