name: imagecraft
base: core24
summary: Imagecraft is a craft tool used to create Ubuntu bootable images.
description: |
    Imagecraft is a craft tool used to create Ubuntu bootable images. It follows
    the same principles as snapcraft, but is focused on creating bootable images
    instead.
adopt-info: imagecraft
confinement: classic
grade: devel
license: GPL-3.0
source-code: https://github.com/canonical/imagecraft

platforms:
  amd64:
  arm64:
  armhf:
  riscv64:
  s390x:
  ppc64el:

apps:
  imagecraft:
    command: bin/python $SNAP/bin/imagecraft
    environment:
      PATH: "$SNAP/libexec/imagecraft:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      PERL5LIB: $SNAP/usr/share/perl5:$SNAP/usr/share/perl:$PERL5LIB

build-packages:
  - git
  - libapt-pkg-dev
  - libyaml-dev
  - python3.12-dev
  - python3.12-venv
  - pkg-config
  - python3-pip
  - python3-setuptools
  - python3-wheel
  - python3-venv
  - python3-minimal
  - python3-pkg-resources
  - python3.12-minimal

parts:
  libgit2:
    source: https://github.com/libgit2/libgit2/archive/refs/tags/v1.7.2.tar.gz
    source-checksum: sha256/de384e29d7efc9330c6cdb126ebf88342b5025d920dcb7c645defad85195ea7f
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    build-attributes:
      - enable-patchelf
    build-packages:
      - libssl-dev
    prime:
      - -usr/include
      - -usr/bin
  imagecraft-libs:
    plugin: nil
    build-attributes:
      - enable-patchelf
    stage-packages:
      - apt
      - apt-transport-https
      - apt-utils
      - gpgv
      - libpython3-stdlib
      - libpython3.12-stdlib
      - libpython3.12-minimal
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-pkg-resources
      - python3.12-venv
      - python3.12-minimal
  imagecraft:
    after: [imagecraft-libs, libgit2]
    source: .
    plugin: python
    build-attributes:
      - enable-patchelf
    build-packages:
      - python3.12-dev
      - python3-pip-whl
      - libffi-dev
      - cargo
      - pkg-config
      - git
    python-packages:
      - wheel
      - pip
      - setuptools
    build-environment:
      - PARTS_PYTHON_VENV_ARGS: --system-site-packages
      - PIP_NO_BINARY: ":all:"
    organize:
      bin/craftctl: libexec/imagecraft/craftctl
    override-build: |
      craftctl default
      sed -i -e '1 s|^#!/.*|#!/snap/imagecraft/current/bin/python -E|' $CRAFT_PART_INSTALL/bin/craftctl
      version="$(python3 -c "import imagecraft;print(imagecraft.__version__)")"
      craftctl set version="$version"
