name: imagecraft
base: core24
summary: Imagecraft is a craft tool used to create Ubuntu bootable images.
description: |
    Imagecraft is a craft tool used to create Ubuntu bootable images. It follows
    the same principles as snapcraft, but is focused on creating bootable images
    instead.
adopt-info: imagecraft
confinement: classic
grade: devel
license: GPL-3.0
source-code: https://github.com/canonical/imagecraft

apps:
  imagecraft:
    command: bin/python $SNAP/bin/imagecraft
    environment:
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      DEBOOTSTRAP_DIR: $SNAP/usr/share/debootstrap
      PERL5LIB: $SNAP/usr/share/perl5:$SNAP/usr/share/perl:$PERL5LIB
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH

build-packages:
  - git
  - libapt-pkg-dev
  - libyaml-dev
  - python3.12-dev
  - python3.12-venv
  - pkg-config
  - python3-pip
  - python3-setuptools
  - python3-wheel
  - python3-venv
  - python3-minimal
  - python3-pkg-resources
  - python3.12-minimal

parts:
  imagecraft-libs:
    plugin: nil
    build-attributes:
      - enable-patchelf
    stage-snaps:
      # For now use the latest/edge to make sure we use a core24 based ubuntu-image
      # With python3.12
      - ubuntu-image/latest/edge
    stage-packages:
      - apt
      - apt-transport-https
      - apt-utils
      - gpgv
      - libpython3-stdlib
      - libpython3.12-stdlib
      - libpython3.12-minimal
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - python3-pkg-resources
      - python3.12-venv
      - python3.12-minimal

  imagecraft:
    after: [imagecraft-libs]
    source: .
    plugin: python
    build-attributes:
      - enable-patchelf
    python-packages:
      - wheel
      - pip
      - setuptools
    python-requirements:
      - requirements.txt
    build-environment:
      - "PARTS_PYTHON_INTERPRETER": "python3.12"
      - "CFLAGS": "$(pkg-config python-3.12 yaml-0.1 --cflags)"
    override-build: |
      python3 --version
      craftctl default
      version="$(python3 setup.py --version)"
      # Fix pyvenv.cfg until it is fixed in craft libs
      sed -i "${CRAFT_PART_INSTALL}/pyvenv.cfg" \
          -e 's@^home = '"${CRAFT_STAGE}"'/usr/bin$@home = /snap/imagecraft/current/usr/bin@g'
      sed -i '\,^executable = ,d' "${CRAFT_PART_INSTALL}/pyvenv.cfg"
      sed -i '\,^command = ,d' "${CRAFT_PART_INSTALL}/pyvenv.cfg"

      craftctl set version="$version"
