name: Update Copilot Instructions
on:
  schedule:
    - cron: "0 9 * * 1" # Run every Monday at 09:00 UTC
  workflow_dispatch:

permissions: {}

jobs:
  check-update:
    permissions:
      contents: write
      pull-requests: write
    uses: canonical/copilot-collections/.github/workflows/auto_update_collections.yaml@d41d8d915a3f9cd5cb95d62b188e849c62c54418
