name: QA
on:
  push:
    branches:
      - "main"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "renovate/*"
  pull_request:

jobs:
  lint:
    uses: canonical/starflow/.github/workflows/lint-python.yaml@main
  test:
    uses: canonical/starflow/.github/workflows/test-python.yaml@work/missing-uv-python
    with:
      lowest-python-version: ""
      fast-test-platforms: '["noble"]'
      fast-test-python-versions: '["3.12", "3.13"]'
      slow-test-platforms: '["noble"]'
      slow-test-python-versions: '["3.12"]'
