name: Snap

on:
  pull_request:
  push:
    branches:
      - "feature/**"
  # allow manual re-publishing as branches expire after 30 days
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decision to Publish
        id: decisions
        run: |
          # Secrets cannot be used in conditionals, so this is our dance:
          # https://github.com/actions/runner/issues/520
          if [[ -n "${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}" ]]; then
            echo PUBLISH=true >> $GITHUB_OUTPUT
          else
            echo PUBLISH= >> $GITHUB_OUTPUT
          fi
      - if: steps.decisions.outputs.PUBLISH == 'true'
        name: Checkout imagecraft
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - if: steps.decisions.outputs.PUBLISH == 'true'
        name: Build imagecraft snap
        uses: canonical/action-build@v1
        id: build-imagecraft

      - if: steps.decisions.outputs.PUBLISH == 'true'
        name: Upload imagecraft snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.build-imagecraft.outputs.snap }}

      - name: Get branch name
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]
          then
            echo "branch=pr-${{ github.event.number }}" >> "$GITHUB_OUTPUT"
          else
            branch=$(echo ${GITHUB_REF#refs/*/} | sed -e 's|feature/\(.*\)|\1|')
            echo "branch=$branch" >> "$GITHUB_OUTPUT"
          fi

      - if: steps.decisions.outputs.PUBLISH == 'true'
        name: Publish feature branch to edge/${{ steps.vars.outputs.branch }}
        uses: canonical/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.build-imagecraft.outputs.snap }}
          release: edge/${{ steps.vars.outputs.branch }}
