name: test
on:
  push:
    branches:
      - "main"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Configure environment
        run: |
          echo "::group::Begin snap install"
          echo "Installing snaps in the background while running apt and pip..."
          sudo snap install --no-wait --classic pyright
          sudo snap install --no-wait shellcheck
          echo "::endgroup::"
          echo "::group::pip install"
          python -m pip install tox
          echo "::endgroup::"
          echo "::group::Create virtual environments for linting processes."
          tox run -m lint --notest
          echo "::endgroup::"
          echo "::group::Wait for snap to complete"
          snap watch --last=install
          echo "::endgroup::"
      - name: Run Linters
        run: tox run --skip-pkg-install --no-list-dependencies -m lint
  unit:
    strategy:
      matrix:
        platform: [ubuntu-20.04, ubuntu-22.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.8
            3.10
            3.11
            3.12-dev
          cache: 'pip'
      - name: Configure environment
        run: |
          echo "::group::pip install"
          python -m pip install tox
          echo "::endgroup::"
          mkdir -p results
      - name: Setup Tox environments
        run: tox run -m tests --notest
      - name: Test with tox
        run: tox run --skip-pkg-install --no-list-dependencies --result-json results/tox-${{ matrix.platform }}.json -m unit-tests
        env:
          PYTEST_ADDOPTS: "--no-header -vv -rN"
      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./results/
          files: coverage*.xml
      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.platform }}
          path: results/
  integration:
    strategy:
      matrix:
        platform: [ubuntu-20.04, ubuntu-22.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.8
            3.10
            3.11
            3.12-dev
          cache: 'pip'
      - name: Configure environment
        run: |
          echo "::group::pip install"
          python -m pip install tox
          echo "::endgroup::"
          mkdir -p results
      - name: Setup Tox environments
        run: tox run -m tests --notest
      - name: Test with tox
        run: tox run --skip-pkg-install --no-list-dependencies --result-json results/tox-${{ matrix.platform }}.json -m integration-tests
        env:
          PYTEST_ADDOPTS: "--no-header -vv -rN"
      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.platform }}
          path: results/
